image: Visual Studio 2017

platform: Any CPU
configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  except:
    - gh-pages

install:
# Ensure downloads folder exists.
  - cmd: if not exist "c:\downloads" mkdir "c:\downloads"

# The current versions of OpenCover do not support the new PDB format - download a pre-release version which does.
  - cmd: if not exist "c:\downloads\OpenCover.zip" appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/xj78v6dac42uob8q/artifacts/main/bin/zip/opencover.4.6.589.zip -FileName "c:\downloads\OpenCover.zip" # OpenCover 4.6.589.zip
  - cmd: 7z x c:\downloads\OpenCover.zip -oc:\OpenCover\

build_script:
  - ps: dotnet --info
  - ps: dotnet build -c $ENV:CONFIGURATION

test_script: 
  - ps: .\build\scripts\run-tests.ps1
  - cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - cmd: pip install codecov
  - cmd: codecov -f "%APPVEYOR_BUILD_FOLDER%\artifacts\opencoverCoverage.xml"

after_build:
  - ps: .\build\scripts\create-packages.ps1

artifacts:
  - path: 'artifacts\packages\*.nupkg'

cache:
  - c:\downloads\OpenCover.zip -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> *.csproj, appveyor.yml'